name: buildPDFs

on: 
  push:

jobs:
  converttopdf:
    name: Build PDFs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate PDFs
        run: |-
          npm install -g md-to-pdf
          cd Documentation/Procedures/Tags
          mkdir -p _output
          echo; echo "Files in Documentation Folder"
          ls
          echo; echo "Generating PDFs"
          for f in *.md; do md-to-pdf "$f"; done;
          echo; echo "Moving PDFs to output"
          for f in *.pdf; do mv "$f" _output/; done;
          cd _output
          echo; echo "Ouput Folder Listing"
          ls
        
      - uses: actions/upload-artifact@v1
        with:
          name: Documentation/Procedures/Tags/pdfs
          path: Documentation/Procedures/Tags/_output
